# Generated by Django 3.2.21 on 2024-02-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0002_auto_20240211_1851'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
