# Generated by Django 3.2.21 on 2024-02-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0003_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
