# Generated by Django 3.2.21 on 2024-02-12 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inquiries', '0004_enquiry_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='accepted',
        ),
    ]
